# Generated by Django 2.1.2 on 2019-05-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_root', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AndroidManifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AndroidRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('branch', models.CharField(max_length=255)),
                ('manifest', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BranchTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('template', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Build2Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Build')),
                ('init', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.AndroidRepo')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CherrypickPatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeid', models.CharField(max_length=24)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Build')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_dir', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('config_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JenkinsHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('jenkins_user', models.CharField(max_length=255)),
                ('jenkins_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JenkinsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=255)),
                ('job_params', models.CharField(max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.JenkinsHost')),
            ],
        ),
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('current_baseline', models.CharField(max_length=32)),
                ('base_kernel', models.CharField(max_length=32)),
                ('category', models.CharField(default=None, max_length=16, null=True)),
                ('classification', models.CharField(default='Confidential', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='KernelRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel')),
            ],
        ),
        migrations.CreateModel(
            name='KernelRepoSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel')),
            ],
        ),
        migrations.CreateModel(
            name='KernelRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel_root', models.CharField(max_length=255)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.CPU')),
                ('kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel')),
            ],
        ),
        migrations.CreateModel(
            name='MakeTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_targets', models.CharField(max_length=255)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Build')),
            ],
        ),
        migrations.CreateModel(
            name='MixinConfigDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_dir_in_mixin', models.CharField(max_length=255)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.CPU')),
                ('kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel')),
            ],
        ),
        migrations.CreateModel(
            name='RegExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('pattern', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_name', models.CharField(max_length=255)),
                ('remote_branch', models.CharField(max_length=255)),
                ('push_method', models.CharField(max_length=255)),
                ('force_push', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Release')),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Remote')),
            ],
        ),
        migrations.CreateModel(
            name='RepoRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Release')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=16, null=True)),
                ('host', models.CharField(max_length=255, null=True)),
                ('project', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repotype', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StagingBranchTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Repository')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.BranchTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TagTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=255)),
                ('kernel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackerBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Domain')),
                ('kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsid', models.CharField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('ldap_domain', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='repotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.RepoType'),
        ),
        migrations.AddField(
            model_name='reporelease',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Repository'),
        ),
        migrations.AddField(
            model_name='remote',
            name='dst_repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_repo', to='framework.Repository'),
        ),
        migrations.AddField(
            model_name='remote',
            name='kernelrelease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.KernelRelease'),
        ),
        migrations.AddField(
            model_name='remote',
            name='src_repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_repo', to='framework.Repository'),
        ),
        migrations.AddField(
            model_name='kernelreposet',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Repository'),
        ),
        migrations.AddField(
            model_name='kernelrelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Release'),
        ),
        migrations.AddField(
            model_name='jenkinsjob',
            name='kernel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel'),
        ),
        migrations.AddField(
            model_name='domain',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.User'),
        ),
        migrations.AddField(
            model_name='configdir',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.CPU'),
        ),
        migrations.AddField(
            model_name='configdir',
            name='kernel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel'),
        ),
        migrations.AddField(
            model_name='build',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.CPU'),
        ),
        migrations.AddField(
            model_name='build',
            name='kernel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel'),
        ),
        migrations.AddField(
            model_name='build',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Target'),
        ),
        migrations.AddField(
            model_name='androidconfig',
            name='kernel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel'),
        ),
        migrations.AlterUniqueTogether(
            name='mixinconfigdir',
            unique_together={('kernel', 'cpu')},
        ),
        migrations.AlterUniqueTogether(
            name='kernelroot',
            unique_together={('kernel', 'cpu')},
        ),
        migrations.AlterUniqueTogether(
            name='kernelreposet',
            unique_together={('kernel', 'repo')},
        ),
        migrations.AlterUniqueTogether(
            name='kernelrelease',
            unique_together={('release', 'kernel')},
        ),
        migrations.AlterUniqueTogether(
            name='configdir',
            unique_together={('kernel', 'cpu')},
        ),
        migrations.AlterUniqueTogether(
            name='build2repo',
            unique_together={('build', 'init')},
        ),
        migrations.AlterUniqueTogether(
            name='build',
            unique_together={('kernel', 'cpu', 'target')},
        ),
    ]
