# Generated by Django 2.1.2 on 2019-05-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtemplate',
            name='kernel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel'),
        ),
    ]
