# Generated by Django 2.2.2 on 2019-06-11 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0003_auto_20190604_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_dir', models.CharField(max_length=255)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Build')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Release')),
            ],
            options={
                'unique_together': {('build', 'config_dir')},
            },
        ),
    ]
