# Generated by Django 2.2.2 on 2019-08-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0005_regexp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kernel2Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='framework.Kernel')),
                ('regexp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='framework.RegExp')),
                ('release_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_job', to='framework.JenkinsJob')),
                ('staging_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_job', to='framework.JenkinsJob')),
            ],
        ),
    ]
