# Generated by Django 2.2.2 on 2019-11-07 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0006_kernel2job'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_name', models.CharField(max_length=255)),
                ('push_method', models.CharField(max_length=255)),
                ('force_push', models.BooleanField(default=False)),
                ('dst_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_repo_2', to='framework.Repository')),
                ('kernelrelease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.KernelRelease')),
                ('push_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_tmpl', to='framework.BranchTemplate')),
                ('src_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_repo_2', to='framework.Repository')),
                ('staging_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_tmpl', to='framework.BranchTemplate')),
            ],
        ),
    ]
