from django.contrib import admin

# Register your models here.
from .models import *

admin.site.register(ApplicationType)
admin.site.register(ArtifactPattern)
admin.site.register(ArtifactTarget)
admin.site.register(CredentialType)
admin.site.register(JenkinsHost)
admin.site.register(Kernel)
admin.site.register(KTemplate)
admin.site.register(Platform)
admin.site.register(RegExp)
admin.site.register(Release)
admin.site.register(Repository)
admin.site.register(RepoType)
admin.site.register(Subdomain)
admin.site.register(User)
admin.site.register(Application)
admin.site.register(BranchTemplate)
admin.site.register(CoverityProject)
admin.site.register(Credential)
admin.site.register(Domain)
admin.site.register(DomainOwner)
admin.site.register(JenkinsJob)
admin.site.register(KernelRelease)
admin.site.register(KernelRepoSet)
admin.site.register(TagTemplate)
admin.site.register(TrackerBranch)
admin.site.register(Artifacts)
admin.site.register(PathToDomain)
admin.site.register(Remote)
admin.site.register(ScmTrigger)
admin.site.register(ScmEvent)
admin.site.register(YoctoBSP)
admin.site.register(YoctoBuild)
admin.site.register(StableKernel)
admin.site.register(ProductType)
admin.site.register(ProductVariant)
admin.site.register(KernelProduct)

